### ISSUE TITLE
How to solve those page that got no submit button

### ISSUE THREAD

**Issue by spushpendra2000** [entrptaher/2captchasolver#1]
I am using 2captcha but i am landing on the page that is showing recaptchav2 but there is not submit button. i can see the callback function. Do you know how to solve this in node.js

**Comment by spushpendra2000** [comment]
Nevermind, await page.solveRecaptchas() is resolving the page. 
However, if i do await page.content(); after solveRecaptchas, i see the error
Error: Execution context was destroyed, most likely because of a navigation.

**Comment by entrptaher** [comment]
How about waiting for navigation?

```js
await Promise.all([
 page.solveRecaptchas(),
 page.waitForNavigation()
])
```

It will wait for both.

**Comment by spushpendra2000** [comment]
Thankts
